#!/bin/bash
# Quick Configuration Checklist for Bookify

echo "========================================="
echo "  BOOKIFY - STRIPE & NODEMAILER SETUP"
echo "========================================="
echo ""

echo "📋 BEFORE YOU START:"
echo "  1. You need a Stripe account: https://stripe.com"
echo "  2. You need a Brevo account: https://www.brevo.com"
echo "  3. Have your verified email address ready"
echo ""

echo "========================================="
echo "  STEP 1: STRIPE CONFIGURATION"
echo "========================================="
echo ""
echo "1.1 Get Your Stripe Keys:"
echo "    • Go to: https://dashboard.stripe.com/apikeys"
echo "    • Copy your Publishable Key (starts with pk_test_)"
echo "    • Copy your Secret Key (starts with sk_test_)"
echo ""
echo "1.2 Set Up Webhook:"
echo "    • Go to: https://dashboard.stripe.com/webhooks"
echo "    • Click 'Add Endpoint'"
echo "    • URL: https://yourdomain.com/api/stripe"
echo "    • Events: Select 'checkout.session.completed'"
echo "    • Copy Signing Secret (starts with whsec_)"
echo ""
echo "1.3 Add to .env file:"
echo "    STRIPE_PUBLISHABLE_KEY=pk_test_YOUR_KEY_HERE"
echo "    STRIPE_SECRET_KEY=sk_test_YOUR_KEY_HERE"
echo "    STRIPE_WEBHOOK_SECRET=whsec_YOUR_SECRET_HERE"
echo ""

echo "========================================="
echo "  STEP 2: BREVO (EMAIL) CONFIGURATION"
echo "========================================="
echo ""
echo "2.1 Create Brevo Account:"
echo "    • Go to: https://www.brevo.com"
echo "    • Sign up and verify your email"
echo ""
echo "2.2 Get SMTP Credentials:"
echo "    • Go to: https://app.brevo.com/settings/smtp-api"
echo "    • SMTP Server: smtp-relay.brevo.com"
echo "    • Port: 587"
echo "    • Login: your_email@example.com"
echo "    • Password: Get from SMTP settings"
echo ""
echo "2.3 Add to .env file:"
echo "    SENDER_EMAIL=your_verified_email@example.com"
echo "    SMTP_USER=your_email@example.com"
echo "    SMTP_PASS=your_brevo_smtp_password"
echo ""

echo "========================================="
echo "  STEP 3: VERIFY CONFIGURATION"
echo "========================================="
echo ""
echo "✓ Check .env file has all values filled in"
echo "✓ Restart your server: npm run dev"
echo "✓ Test payment flow with Stripe test card: 4242 4242 4242 4242"
echo ""

echo "========================================="
echo "  TESTING CHECKLIST"
echo "========================================="
echo ""
echo "Payment Test:"
echo "  1. Create a new booking"
echo "  2. Go to My Bookings"
echo "  3. Click 'Pay Now'"
echo "  4. Use test card: 4242 4242 4242 4242"
echo "  5. Any future date and any CVC"
echo "  6. Check if booking status changes to 'Paid'"
echo ""
echo "Email Test:"
echo "  1. Create a new booking"
echo "  2. Check your email inbox"
echo "  3. Look for booking confirmation"
echo "  4. Check spam folder if not found"
echo ""

echo "========================================="
echo "  TROUBLESHOOTING"
echo "========================================="
echo ""
echo "Payment not working?"
echo "  • Check STRIPE_SECRET_KEY starts with 'sk_test_'"
echo "  • Check STRIPE_WEBHOOK_SECRET is correct"
echo "  • Check webhook URL matches your domain"
echo "  • Check server logs for errors"
echo ""
echo "Email not sending?"
echo "  • Check SENDER_EMAIL is verified in Brevo"
echo "  • Check SMTP_USER and SMTP_PASS are correct"
echo "  • Check Brevo account is active"
echo "  • Check server logs for SMTP errors"
echo ""
echo "Status stuck on 'Unpaid'?"
echo "  • Make payment through Stripe"
echo "  • Check webhook received the payment event"
echo "  • Check server logs for webhook errors"
echo ""

echo "========================================="
echo "  NEED HELP?"
echo "========================================="
echo ""
echo "See detailed guides:"
echo "  • STRIPE_NODEMAILER_SETUP.md - Complete setup guide"
echo "  • ISSUES_AND_FIXES_SUMMARY.md - What was fixed"
echo ""
echo "========================================="
